name: Build and Package WakfuStats

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Create native installer with jpackage
        run: |
          mkdir jpackage-output
          jpackage \
            --input target \
            --main-jar wakfustats.jar \
            --name WakfuStats \
            --main-class wakfustats.WakfuStatsLauncher \
            --type ${{ steps.package-type.outputs.type }} \
            --dest jpackage-output \
            --app-version 1.0.0
        shell: bash
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Determine jpackage type
        id: package-type
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "type=exe" >> $GITHUB_OUTPUT
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "type=dmg" >> $GITHUB_OUTPUT
          else
            echo "type=deb" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: wakfustats-${{ matrix.os }}-jar
          path: target/*.jar

      - name: Upload Native Package
        uses: actions/upload-artifact@v3
        with:
          name: wakfustats-${{ matrix.os }}-installer
          path: jpackage-output/*
